name: astrea
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.04+1

environment:
  sdk: ^3.8.1

workspace:
  - package/upload


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: 0.19.0
  get: 4.7.2
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0
  auto_size_text: 3.0.0
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  flutter_screenutil: 5.9.3
  flutter_rating_bar: 4.0.1
  keyboard_visibility_pro: ^1.0.0
  bubble_box: ^0.5.3
  pull_to_refresh: 2.0.0
  flutter_easyloading: 3.0.5
  permission_handler: 12.0.1
  screen_protector: 1.4.2+1
  flutter_slidable: 4.0.0
  wheel_picker: 0.2.2
  flutter_image_compress: 2.4.0
  intl_country_data: 1.2.9
  bubble_tab_indicator: 0.1.6
  event_bus: ^2.0.1
  logger: 2.6.0
  flutter_svg: ^2.2.0
  url_launcher: 6.3.2
  image_picker: 1.1.2
  path_provider: 2.1.5
  google_sign_in: 6.3.0
  sign_in_with_apple: 7.0.1
  email_validator: 3.0.0
  sprintf: 7.0.0
  collection: 1.19.1
  lottie: 3.3.1
  dio_cache_interceptor: 4.0.3
  azlistview_plus: 3.0.0
  scrollable_positioned_list: 0.3.8
  #scroll_to_position: ^0.0.2
  webview_flutter: 4.13.0
  #ios 的设备号能拿到
  device_info_plus: 11.5.0
  android_id: 0.4.0
  #package_info_plus: 8.3.0
  video_player: 2.10.0
  #判断是否支持google服务
  google_api_availability: 5.0.1
  #连字符
  auto_hyphenating_text: ^0.3.1
  percent_indicator: 4.2.5
  #虚线
  dotted_dashed_line: 0.0.3
  #虚线
  dotted_decoration: 2.0.0
  #通知
  #firebase_messaging: 16.0.0
  #notification_permissions: 0.6.1
  #flutter_local_notifications: 19.4.0
  #read more
  #readmore_flutter: ^1.1.3






 #抓包工具
  proxy:
    path: tools/proxy

  awesome_datetime_picker:
    path: plugins/awesome_datetime_picker-master

  custom_navigation_bar:
    path: plugins/custom_bubble_navigation_bar-master


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/video/
    - assets/json/
    - assets/time/
    - assets/image/
    - assets/images/
    - assets/data/
    - assets/background/

  fonts:
    - family: AVENIR-BLACK
      fonts:
        - asset: fonts/AVENIR-BLACK-3.ttf
    - family: Avenir-Medium
      fonts:
        - asset: fonts/Avenir-Medium-6.otf